live_config_reload = true

[colors.primary]
background = "#000000"
foreground = "#eeeeee"

[font]
size = 13

[font.normal]
family = "Source Code Pro"

[scrolling]
history = 100000

[window]
opacity = 0.8
startup_mode = "Maximized"
