#!/usr/bin/env sh

HOOK_BASEDIR="$(git rev-parse --show-toplevel)"/.git/hooks
GITHOOK_BASEDIR="$(dirname "$(readlink -f "$0")")"

for f in "$HOOK_BASEDIR"/*.sample; do
	SAMPLE_NAME="$(basename "$f")"
	HOOK_TYPE="${SAMPLE_NAME%%.*}"
	printf "%s\n" "Creating link from '$HOOK_BASEDIR/$HOOK_TYPE' to '$GITHOOK_BASEDIR/run-hook'."
	ln -f -s -r "$GITHOOK_BASEDIR/run-hook" "$HOOK_BASEDIR/$HOOK_TYPE"
done
