# Quickly display file contents.
abbr -a b 'bat'

abbr -a G    'git status'
abbr -a Ga   'git add'
abbr -a Gaa  'git add -Av'
abbr -a Gap  'git add --patch'
abbr -a Gb   'git branch'
abbr -a Gbl  'git --no-pager branch --verbose --list --all'
abbr -a Gc   'git commit'
abbr -a Gcs  'git commit --gpg-sign'
abbr -a Gca  'git commit --amend'
abbr -a Gcas 'git commit --amend --gpg-sign'
abbr -a Gco  'git checkout'
abbr -a Gd   'git diff'
abbr -a Gdf  'git diff'
abbr -a Gds  'git diff --staged'
abbr -a Gfh  'git log --follow -p -- '
abbr -a Gh   'git history'
abbr -a Gl   'git log'
abbr -a Gp   'git pull'
abbr -a GP   'git push'
abbr -a Gr   'git remote -v'
abbr -a Gs   'git status --short'
abbr -a GS   'git show'
abbr -a Gt   'git tree'
abbr -a Gu   'git reset --soft HEAD~1'

abbr -a lg 'lazygit'
