fish_add_path "$HOME/bin"
fish_add_path "$HOME/.local/bin"
fish_add_path "$HOME/.nimble/bin"
fish_add_path "$GOPATH/bin"
fish_add_path "$DOTFILES/bin"
fish_add_path "$CARGO_HOME/bin"
fish_add_path "$PNPM_HOME"
