fps
frametime

cpu_stats
cpu_temp
cpu_mhz

core_load
core_bars

gpu_load
gpu_stats
gpu_core_clock
gpu_temp

vram
gpu_mem_temp

table_columns=4
background_alpha=0.65
round_corners=3
font_size=12
hud_no_margin

position=top-right
offset_x=-8
offset_y=55
