#!/usr/bin/env bash

set -e

TMP_DIR=$(mktemp -d)

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

DST_DIRECTORY="$XDG_DATA_HOME/nvim/site/spell"

if ! [ -d "$DST_DIRECTORY" ]; then
	if ! mkdir -p "$DST_DIRECTORY"; then
		printf "%s\n" 'Cannot create spell directory.' >&2
		exit 1
	fi
fi

download_asset_url () {
	base="$1"
	lang_region="$2"
	extension="$3"

	curl -q -s -S -L -o "$TMP_DIR/$lang_region.$extension" "https://github.com/LibreOffice/dictionaries/raw/master/$base/$lang_region.$extension"
}

for language in 'en_US' 'de_DE_frami'; do
	base="$(printf '%s' "$language" | cut -d '_' -f 1)"

	for lang_region in $language; do
		printf "Downloading dictionaries for '%s'...\n" "$lang_region"
		download_asset_url "$base" "$lang_region" 'aff'
		download_asset_url "$base" "$lang_region" 'dic'
	done

	# https://stackoverflow.com/a/19657765
	lang_regions=( $language )

	# https://stackoverflow.com/a/13216833
	lang_regions=( "${lang_regions[@]/#/$TMP_DIR\/}" )

	# https://stackoverflow.com/a/13471141
	lang_regions="${lang_regions[*]// /|}"

	printf "Generating language file for '%s'...\n" "$base"
	nvim --headless -c "silent mkspell! $DST_DIRECTORY/$base $lang_regions" -c 'quitall!'
done

rm -r "$TMP_DIR"
