# This file is read for interactive shells in zsh.

# The path is not set by the zshenv file.
source "$ZSH_CONFIG/path.zsh"

# Source custom options and aliases.
foreach file (
	misc
	completion
	directory
	clip
	widget
	unbind
	mapping
	prompt
) {
	source "$ZSH_CONFIG/$file.zsh"
}
unset file

if [ -e "$ZSH_CONFIG/local.zsh" ]; then
	source "$ZSH_CONFIG/local.zsh"
fi

# Source all available aliases.
for file in "$ZSH_CONFIG"/alias/**/*.zsh; do
	source $file
done
unset file

# Source all available functions.
for file in "$ZSH_CONFIG"/function/**/*.zsh; do
	source $file
done
unset file

# Start tmux if the current shell is not inside one.
if [ -x "$(command -v tmux)" ]; then
	[[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
fi

# GPG needs to have this environment variable set.
# SEE https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html
export GPG_TTY=$(tty)

# Setup hooks for direnv.
if [ -x "$(command -v direnv)" ]; then
	eval "$(direnv hook zsh)"
fi

# Source plugins.
source "$ZSH_CONFIG/plugin.zsh"
if [ -f "$ZSH_CONFIG/plugin/autopair/autopair.zsh" ]; then
	source "$ZSH_CONFIG/plugin/autopair/autopair.zsh"
fi
if [ -f "$ZSH_CONFIG/plugin/autosuggestions/zsh-autosuggestions.zsh" ]; then
	source "$ZSH_CONFIG/plugin/autosuggestions/zsh-autosuggestions.zsh"
fi
if [ -f "$ZSH_CONFIG/plugin/forgit/forgit.plugin.zsh" ]; then
	source "$ZSH_CONFIG/plugin/forgit/forgit.plugin.zsh"
fi
if [ -f "$ZSH_CONFIG/plugin/syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
	source "$ZSH_CONFIG/plugin/syntax-highlighting/zsh-syntax-highlighting.zsh"
fi
