alias Dcl='sudo docker container list -a'
alias Dcr='sudo docker rm'
alias  Dd='sudo docker stop'
alias Dil='sudo docker image list -a'
alias Dir='sudo docker rmi'
alias Dip='sudo docker rmi $(sudo docker images --quiet --filter "dangling=true")'
alias  Dp='sudo docker pull'
alias  Ds='sudo docker start'
alias  Du='sudo docker update'
