alias    G='git status'
alias   Ga='git add'
alias  Gaa='git add -Av'
alias  Gap='git add --patch'
alias   Gb='git branch'
alias  Gbl='git --no-pager branch --verbose --list --all'
alias   Gc='git commit'
alias  Gcs='git commit --gpg-sign'
alias  Gca='git commit --amend'
alias Gcas='git commit --amend --gpg-sign'
alias  Gco='git checkout'
alias   Gd='git diff'
alias  Gdf='git diff'
alias  Gds='git diff --staged'
alias  Gfh='git log --follow -p -- '
alias   Gh='git history'
alias   Gl='git log'
alias   Gp='git pull'
alias   GP='git push'
alias   Gr='git remote -v'
alias   Gs='git status --short'
alias   GS='git show'
alias   Gt='git tree'
alias   Gu='git reset --soft HEAD~1'

# Manage Git repositories.
alias mr='mr -d $GIT_ROOT'
